"""add uuid identifiers to reports

Revision ID: 3af410d49803
Revises: 49dbc0045d85
Create Date: 2026-09-16 03:00:30.976745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af410d49803'
down_revision: Union[str, None] = '49dbc0045d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reports_uuid'), 'reports', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_uuid'), table_name='reports')
    # ### end Alembic commands ###
