"""add uuid identifiers to leave requests

Revision ID: 49dbc0045d85
Revises: 5befecffc0a5
Create Date: 2026-09-16 02:56:50.798205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dbc0045d85'
down_revision: Union[str, None] = '5befecffc0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leave_requests_uuid'), 'leave_requests', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_uuid'), table_name='leave_requests')
    # ### end Alembic commands ###
