"""add uuid identifiers to attendance

Revision ID: 5befecffc0a5
Revises: c37a0f4b4e8a
Create Date: 2026-09-16 02:53:49.393353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5befecffc0a5'
down_revision: Union[str, None] = 'c37a0f4b4e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendance_uuid'), 'attendance', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_uuid'), table_name='attendance')
    # ### end Alembic commands ###
