"""add uuid identifiers to tasks

Revision ID: 6fc735544244
Revises: ee0efaaa2029
Create Date: 2026-09-16 02:44:38.204780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc735544244'
down_revision: Union[str, None] = 'ee0efaaa2029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_uuid'), 'tasks', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_uuid'), table_name='tasks')
    # ### end Alembic commands ###
