"""add UUID identifiers to departments

Revision ID: bce7d547bb0f
Revises: f4af0fa9a591
Create Date: 2026-09-16 02:23:10.400161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce7d547bb0f'
down_revision: Union[str, None] = 'f4af0fa9a591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_departments_uuid'), 'departments', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_uuid'), table_name='departments')
    # ### end Alembic commands ###
