"""add uuid identifiers to task history

Revision ID: c37a0f4b4e8a
Revises: 6fc735544244
Create Date: 2026-09-16 02:49:49.359198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37a0f4b4e8a'
down_revision: Union[str, None] = '6fc735544244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_history_uuid'), 'task_history', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_uuid'), table_name='task_history')
    # ### end Alembic commands ###
