"""add uuid identifiers to notifications

Revision ID: c53dbd682746
Revises: 3af410d49803
Create Date: 2026-09-16 03:03:25.134065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53dbd682746'
down_revision: Union[str, None] = '3af410d49803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    # ### end Alembic commands ###
