"""add UUID identifiers to employees

Revision ID: ee0efaaa2029
Revises: bce7d547bb0f
Create Date: 2026-09-16 02:39:32.097157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0efaaa2029'
down_revision: Union[str, None] = 'bce7d547bb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_uuid'), 'employees', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_uuid'), table_name='employees')
    # ### end Alembic commands ###
